services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: medusa-server-default
    depends_on:
      - postgres
      - redis
    restart: "unless-stopped"
    environment:
      PORT: 9000
    ports:
      - "9000:9000"
    volumes:
      - .:/app/medusa

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medusa-docker

  redis:
    image: redis
    container_name: medusa-cache
    expose:
      - 6379